// old_project/src/components/feedback/ValuationGroupCard.tsx
import { Heading } from "@/components/ui/heading";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { QuestionRatingRow } from "@/components/feedback/QuestionRatingRow";
import type { GroupAnswersState } from "@/lib/valuation-types";

type ValuationGroupCardProps = {
  group: {
    id: number;
    title: string;
    questions: { id: number; questionText: string }[];
  };
  groupAnswers: GroupAnswersState;
  onQuestionRatingChange: (
    groupId: number,
    questionId: number,
    rating: number
  ) => void;
  onGroupCommentChange: (groupId: number, comment: string) => void;
};

export function ValuationGroupCard({
  group,
  groupAnswers,
  onQuestionRatingChange,
  onGroupCommentChange,
}: ValuationGroupCardProps) {
  const groupAnswer = groupAnswers[group.id];
  const groupComment = groupAnswer?.comment || "";

  return (
    <div className="space-y-4 rounded-2xl border bg-card/20 p-5">
      <div className="flex items-start justify-between gap-4">
        <Heading level={3} className="text-base sm:text-lg">
          {group.title}
        </Heading>
      </div>

      <div className="space-y-5 divide-y">
        {group.questions.map((q) => {
          const rating = groupAnswer?.questionAnswers[q.id] ?? null;
          return (
            <QuestionRatingRow
              key={q.id}
              idPrefix={`${group.id}-`}
              questionId={q.id}
              questionText={q.questionText}
              value={rating}
              onChange={(next) => onQuestionRatingChange(group.id, q.id, next)}
            />
          );
        })}
      </div>

      <div className="space-y-2">
        <Label htmlFor={`comment-${group.id}`}>Group Comment (optional)</Label>
        <Textarea
          id={`comment-${group.id}`}
          placeholder="Add optional comment for this group..."
          value={groupComment}
          onChange={(e) => onGroupCommentChange(group.id, e.target.value)}
          rows={3}
        />
      </div>
    </div>
  );
}

// src/lib/components/feedback/valuation-group-card.svelte
<script lang="ts">
  import { Heading } from "$lib/components/ui/heading";
  import { Label } from "$lib/components/ui/label";
  import { Textarea } from "$lib/components/ui/textarea";
  import QuestionRatingRow from "./question-rating-row.svelte";

  type Group = { id: number; title: string; questions: { id: number; questionText: string }[] };

  type Props = {
    group: Group;
    groupAnswers: {
      questionAnswers: Record<number, number>;
      comment: string;
    };
    onQuestionRatingChange: (groupId: number, questionId: number, rating: number) => void;
    onGroupCommentChange: (groupId: number, comment: string) => void;
  };

  let { group, groupAnswers, onQuestionRatingChange, onGroupCommentChange }: Props = $props();

  let commentValue = $state("");

  $effect(() => {
    commentValue = groupAnswers.comment;
  });

  $effect(() => {
    onGroupCommentChange(group.id, commentValue);
  });
</script>

<div class="space-y-4 rounded-2xl border bg-card/20 p-5">
  <Heading level={3} class="text-base sm:text-lg">{group.title}</Heading>

  <div class="space-y-5 divide-y">
    {#each group.questions as q (q.id)}
      <QuestionRatingRow
        questionId={q.id}
        questionText={q.questionText}
        value={groupAnswers.questionAnswers[q.id] ?? null}
        onChange={(next) => onQuestionRatingChange(group.id, q.id, next)}
      />
    {/each}
  </div>

  <div class="space-y-2">
    <Label for={`comment-${group.id}`}>Group Comment (optional)</Label>
    <Textarea id={`comment-${group.id}`} bind:value={commentValue} rows={3}></Textarea>
  </div>
</div>
