// src/lib/components/feedback/question-rating-row.svelte
<script lang="ts">
  import { Label } from '$lib/components/ui/label';
  import RatingSelector from '@/components/ui/rating-selector.svelte';
  import { cn } from '@/utils';

  type Props = {
    class?: string;
    questionId: number;
    questionText: string;
    value: number | null;
    onChange: (rating: number) => void;
  };

  let { class: className = '', questionId, questionText, value, onChange }: Props = $props();
  const labelId = $derived(`rating-label-${questionId}`);
</script>

<div class={cn('grid pb-5 sm:grid-cols-[1fr_320px] sm:items-center', className)}>
  <div class="min-w-0">
    <Label for={labelId} class="leading-snug">{questionText}</Label>
  </div>
  <RatingSelector value={value} onValueChange={onChange} class="justify-end" />
</div>

// old_project/src/components/feedback/QuestionRatingRow.tsx
import { Label } from "@/components/ui/label";
import { RatingSelector } from "@/components/ui/rating-selector";
import { cn } from "@/lib/utils";

type QuestionRatingRowProps = {
  idPrefix?: string;
  questionId: number;
  questionText: string;
  value: number | null;
  onChange: (rating: number) => void;
  className?: string;
};

export function QuestionRatingRow({
  idPrefix,
  questionId,
  questionText,
  value,
  onChange,
  className,
}: QuestionRatingRowProps) {
  const labelId = `rating-label-${idPrefix ?? ""}${questionId}`;

  return (
    <div
      className={cn(
        "grid pb-5 sm:grid-cols-[1fr_320px] sm:items-center",
        className
      )}
    >
      <div className="min-w-0">
        <Label id={labelId} className="leading-snug">
          {questionText}
        </Label>
      </div>
      <RatingSelector
        value={value}
        onValueChange={onChange}
        ariaLabelledby={labelId}
      />
    </div>
  );
}
