// old_project/src/components/ui/multi-select.tsx
"use client";

import * as React from "react";
import { XIcon, CheckIcon } from "lucide-react";
import { cn } from "@/lib/utils";
import { Input } from "./input";
import { Button } from "./button";

interface MultiSelectOption {
  id: number;
  username: string;
}

interface MultiSelectProps {
  options: MultiSelectOption[];
  selected: number[];
  onSelectionChange: (selected: number[]) => void;
  maxSelections?: number;
  placeholder?: string;
  searchPlaceholder?: string;
  emptyMessage?: string;
}

export function MultiSelect({
  options,
  selected,
  onSelectionChange,
  maxSelections = 5,
  placeholder = "Select users...",
  searchPlaceholder = "Search users...",
  emptyMessage = "No users found",
}: MultiSelectProps) {
  const [search, setSearch] = React.useState("");
  const [isOpen, setIsOpen] = React.useState(false);
  const containerRef = React.useRef<HTMLDivElement>(null);

  const filteredOptions = React.useMemo(() => {
    if (!search.trim()) return options;
    const searchLower = search.toLowerCase();
    return options.filter((option) =>
      option.username.toLowerCase().includes(searchLower)
    );
  }, [options, search]);

  const selectedOptions = React.useMemo(() => {
    return options.filter((option) => selected.includes(option.id));
  }, [options, selected]);

  const handleToggle = (optionId: number) => {
    if (selected.includes(optionId)) {
      onSelectionChange(selected.filter((id) => id !== optionId));
    } else {
      if (selected.length < maxSelections) {
        onSelectionChange([...selected, optionId]);
      }
    }
  };

  const handleRemove = (optionId: number) => {
    onSelectionChange(selected.filter((id) => id !== optionId));
  };

  React.useEffect(() => {
    const handleClickOutside = (event: MouseEvent) => {
      if (
        containerRef.current &&
        !containerRef.current.contains(event.target as Node)
      ) {
        setIsOpen(false);
        setSearch("");
      }
    };

    if (isOpen) {
      document.addEventListener("mousedown", handleClickOutside);
      return () => document.removeEventListener("mousedown", handleClickOutside);
    }
  }, [isOpen]);

  return (
    <div ref={containerRef} className="relative w-full">
      <div className="space-y-2">
        <div
          className="flex min-h-9 w-full cursor-pointer items-center gap-2 rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-xs transition-colors hover:bg-accent"
          onClick={() => setIsOpen(!isOpen)}
        >
          <div className="flex flex-1 flex-wrap gap-1.5">
            {selectedOptions.length > 0 ? (
              selectedOptions.map((option) => (
                <span
                  key={option.id}
                  className="inline-flex items-center gap-1 rounded-md bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary"
                >
                  {option.username}
                  <button
                    type="button"
                    onClick={(e) => {
                      e.stopPropagation();
                      handleRemove(option.id);
                    }}
                    className="rounded-sm hover:bg-primary/20"
                  >
                    <XIcon className="h-3 w-3" />
                  </button>
                </span>
              ))
            ) : (
              <span className="text-muted-foreground">{placeholder}</span>
            )}
          </div>
          <span className="text-xs text-muted-foreground">
            {selected.length}/{maxSelections}
          </span>
        </div>

        {isOpen && (
          <div className="absolute z-50 w-full rounded-md border bg-popover shadow-md">
            <div className="p-2">
              <Input
                placeholder={searchPlaceholder}
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="h-8"
                autoFocus
              />
            </div>
            <div className="max-h-60 overflow-auto p-1">
              {filteredOptions.length === 0 ? (
                <div className="px-2 py-6 text-center text-sm text-muted-foreground">
                  {emptyMessage}
                </div>
              ) : (
                filteredOptions.map((option) => {
                  const isSelected = selected.includes(option.id);
                  const isDisabled =
                    !isSelected && selected.length >= maxSelections;

                  return (
                    <button
                      key={option.id}
                      type="button"
                      onClick={() => handleToggle(option.id)}
                      disabled={isDisabled}
                      className={cn(
                        "relative flex w-full cursor-pointer select-none items-center rounded-sm px-2 py-1.5 text-sm outline-none transition-colors",
                        isSelected
                          ? "bg-accent text-accent-foreground"
                          : "hover:bg-accent hover:text-accent-foreground",
                        isDisabled && "opacity-50 cursor-not-allowed"
                      )}
                    >
                      <div className="flex flex-1 items-center gap-2">
                        <div
                          className={cn(
                            "flex h-4 w-4 items-center justify-center rounded-sm border",
                            isSelected
                              ? "border-primary bg-primary text-primary-foreground"
                              : "border-input"
                          )}
                        >
                          {isSelected && (
                            <CheckIcon className="h-3 w-3" />
                          )}
                        </div>
                        <span>{option.username}</span>
                      </div>
                    </button>
                  );
                })
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// src/lib/components/ui/multi-select.svelte
<script lang="ts">
  import { cn } from '@/utils';

  type Option = { id: number; username: string };

  type Props = {
    options: Option[];
    selected?: number[];
    maxSelections?: number;
    placeholder?: string;
    searchPlaceholder?: string;
    emptyMessage?: string;
    class?: string;
  };

  let {
    options,
    selected = $bindable<number[]>([]),
    maxSelections = 5,
    placeholder = 'Select users...',
    searchPlaceholder = 'Search by username...',
    emptyMessage = 'No users found',
    class: className = ''
  }: Props = $props();

  let isOpen = $state(false);
  let search = $state('');
  let container: HTMLDivElement | null = $state(null);

  const selectedOptions = $derived(options.filter((o) => selected.includes(o.id)));
  const filteredOptions = $derived(
    search.trim()
      ? options.filter((o) => o.username.toLowerCase().includes(search.trim().toLowerCase()))
      : options
  );

  function toggle(optionId: number) {
    if (selected.includes(optionId)) {
      selected = selected.filter((id) => id !== optionId);
      return;
    }
    if (selected.length >= maxSelections) return;
    selected = [...selected, optionId];
  }

  function remove(optionId: number) {
    selected = selected.filter((id) => id !== optionId);
  }

  function onDocMouseDown(e: MouseEvent) {
    if (!container) return;
    if (!container.contains(e.target as Node)) {
      isOpen = false;
      search = '';
    }
  }

  $effect(() => {
    if (!isOpen) return;
    document.addEventListener('mousedown', onDocMouseDown);
    return () => document.removeEventListener('mousedown', onDocMouseDown);
  });
</script>

<div bind:this={container} class={cn('relative w-full', className)}>
  <button
    type="button"
    class="flex min-h-9 w-full items-center gap-2 rounded-md border border-input bg-transparent px-3 py-2 text-sm shadow-xs transition-colors hover:bg-accent"
    onclick={() => (isOpen = !isOpen)}
  >
    <div class="flex flex-1 flex-wrap gap-1.5">
      {#if selectedOptions.length > 0}
        {#each selectedOptions as opt (opt.id)}
          <span class="inline-flex items-center gap-1 rounded-md bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
            {opt.username}
            <span
              class="cursor-pointer rounded-sm hover:bg-primary/20"
              role="button"
              tabindex="0"
              onclick={(e) => (e.stopPropagation(), remove(opt.id))}
              onkeydown={(e) => {
                if (e.key === 'Enter' || e.key === ' ') {
                  e.preventDefault();
                  e.stopPropagation();
                  remove(opt.id);
                }
              }}
            >
              ×
            </span>
          </span>
        {/each}
      {:else}
        <span class="text-muted-foreground">{placeholder}</span>
      {/if}
    </div>
    <span class="text-xs text-muted-foreground">{selected.length}/{maxSelections}</span>
  </button>

  {#if isOpen}
    <div class="absolute z-50 mt-2 w-full rounded-md border bg-popover shadow-md">
      <div class="p-2">
        <input
          class="h-8 w-full rounded-md border border-input bg-background px-3 text-sm outline-none focus-visible:ring-2 focus-visible:ring-ring"
          placeholder={searchPlaceholder}
          value={search}
          oninput={(e) => (search = (e.currentTarget as HTMLInputElement).value)}
        />
      </div>
      <div class="max-h-60 overflow-auto p-1">
        {#if filteredOptions.length === 0}
          <div class="px-2 py-6 text-center text-sm text-muted-foreground">{emptyMessage}</div>
        {:else}
          {#each filteredOptions as opt (opt.id)}
            {@const isSelected = selected.includes(opt.id)}
            {@const isDisabled = !isSelected && selected.length >= maxSelections}
            <button
              type="button"
              class={cn(
                'flex w-full items-center justify-between rounded-sm px-2 py-1.5 text-sm transition-colors',
                isSelected ? 'bg-accent text-accent-foreground' : 'hover:bg-accent hover:text-accent-foreground',
                isDisabled && 'opacity-50 cursor-not-allowed'
              )}
              disabled={isDisabled}
              onclick={() => toggle(opt.id)}
            >
              <span>{opt.username}</span>
              <span class="text-xs">{isSelected ? '✓' : ''}</span>
            </button>
          {/each}
        {/if}
      </div>
    </div>
  {/if}
</div>
