// src/routes/login/+page.svelte
<script lang="ts">
  import { enhance } from '$app/forms';
  import { Heading } from '$lib/components/ui/heading';
  import { Card, CardHeader, CardTitle, CardDescription, CardContent } from '$lib/components/ui/card';
  import { Label } from '$lib/components/ui/label';
  import { Input } from '$lib/components/ui/input';
  import { Button } from '$lib/components/ui/button';
  import type { ActionData, PageData } from './$types';

  let { form }: { data: PageData; form: ActionData } = $props();

  let error = $state<string | null>(null);
  $effect(() => {
    error = form?.error ?? null;
  });
</script>

<div class="min-h-screen flex items-center justify-center bg-linear-to-b from-background via-background to-muted/30 px-4 py-10">
  <div class="w-full max-w-md space-y-6">
    <div class="text-center">
      <Heading level={1}>Colleague Feedback</Heading>
      <p class="mt-2 text-sm text-muted-foreground">Sign in to continue</p>
    </div>

    <Card class="w-full rounded-2xl border-0 bg-card/50 shadow-xl ring-1 ring-border/30 backdrop-blur supports-backdrop-filter:bg-card/40">
      <CardHeader>
        <CardTitle>Login</CardTitle>
        <CardDescription>Enter your credentials to access the feedback tool</CardDescription>
      </CardHeader>
      <CardContent>
        <form method="POST" use:enhance class="space-y-4">
          {#if error}
            <div class="rounded-md border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive">
              {error}
            </div>
          {/if}

          <div class="space-y-2">
            <Label for="login-username">Username</Label>
            <Input id="login-username" name="username" autocomplete="username" required />
          </div>

          <div class="space-y-2">
            <Label for="login-password">Password</Label>
            <Input id="login-password" name="password" type="password" autocomplete="current-password" required />
          </div>

          <Button type="submit" class="w-full">Login</Button>

          <div class="text-center text-sm text-muted-foreground">
            Don't have an account?
            <a href="/register" class="text-primary underline-offset-4 hover:underline">Register</a>
          </div>
        </form>
      </CardContent>
    </Card>
  </div>
</div>

// old_project/src/components/Login.tsx
import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";

interface LoginProps {
  onSuccess: () => void;
  onSwitchToRegister: () => void;
}

export function Login({ onSuccess, onSwitchToRegister }: LoginProps) {
  const queryClient = useQueryClient();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError("");
    setLoading(true);

    try {
      const { data, error: apiError } = await api.api.login.post({
        username,
        password,
      });

      if (apiError) {
        setError(apiError?.value?.message || "Login failed. Please try again.");
        return;
      }

      if (data && "error" in data && data.error) {
        setError(data.error);
      } else if (data && "success" in data && data.success) {
        queryClient.invalidateQueries();
        onSuccess();
      } else {
        setError("Login failed. Please try again.");
      }
    } catch (err) {
      console.error("Login error:", err);
      setError(
        err instanceof Error ? err.message : "Login failed. Please try again."
      );
    } finally {
      setLoading(false);
    }
  };

  return (
    <Card className="w-full rounded-2xl border-0 bg-card/50 shadow-xl ring-1 ring-border/30 backdrop-blur supports-backdrop-filter:bg-card/40">
      <CardHeader>
        <CardTitle>Login</CardTitle>
        <CardDescription>
          Enter your credentials to access comments
        </CardDescription>
      </CardHeader>
      <CardContent>
        <form onSubmit={handleSubmit} className="space-y-4">
          {error && (
            <div className="rounded-md border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive">
              {error}
            </div>
          )}
          <div className="space-y-2">
            <Label htmlFor="login-username">Username</Label>
            <Input
              id="login-username"
              placeholder="Enter your username"
              value={username}
              onChange={(e) => setUsername(e.target.value)}
              required
              disabled={loading}
              autoComplete="username"
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="login-password">Password</Label>
            <Input
              id="login-password"
              type="password"
              placeholder="Enter your password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              required
              disabled={loading}
              autoComplete="current-password"
            />
          </div>
          <Button type="submit" className="w-full" disabled={loading}>
            {loading ? "Logging in..." : "Login"}
          </Button>
          <div className="text-center text-sm text-muted-foreground">
            Don't have an account?{" "}
            <Button
              type="button"
              onClick={onSwitchToRegister}
              variant="link"
              className="h-auto p-0 align-baseline"
            >
              Register
            </Button>
          </div>
        </form>
      </CardContent>
    </Card>
  );
}
